name: clustering_covid
channels:
  - defaults
  - menpo
  - conda-forge
dependencies:
  - jupyter=1.0
  - matplotlib=3.3
  - scipy=1.5
  - scikit-learn=0.23
  - pandas=1.1
  - plotly=4.11
  - seaborn=0.11
  - umap-learn=0.4
  - hdbscan=0.8
  - country_converter=0.7
  - pip
  - pip:
    - world-bank-data
